### ISSUE TITLE
vendor hangs on "vendor add golang.org/x/net" and similar

### ISSUE THREAD

**Issue by dmitris** [kardianos/vendor-spec#1]
When running "vendor add golang.org/x/net", it hangs with no output for a long time and CPU goes to 110+ % (on Mac 10.10.3).  Would it be worth to add "-v" switch for verbose mode so that you would be able to see what vendor is doing and which steps are currently running?

![screen shot 2015-04-17 at 12 12 45 pm](https://cloud.githubusercontent.com/assets/31205/7200220/1cc0cd48-e4fb-11e4-986a-f383e37d6229.png)

**Comment by kardianos** [comment]
It would be worth doing. Is osx case insensitive? If so Darwin should be
added to rewrite/path.go.

**Comment by kardianos** [comment]
Can you pull the latest in "vendor" and see if it still hangs?

**Comment by kardianos** [comment]
Closing here. If this is still a problem then please open another issue here: https://github.com/kardianos/vendor/issues .
Thanks.
