### ISSUE TITLE
Consider requiring tools to preserve all unrecognized fields

### ISSUE THREAD

**Issue by kr** [kardianos/vendor-spec#10]
The spec currently says:

> Tool field
> 
> A vendor tool is allowed to write a superset of fields in the file.

It seems possible that multiple tools will be used to process the same repo. For example, one tool (e.g. `vendor`) might be useful to vendor code and rewrite import paths, while another tool (e.g. `godep restore`) might be useful to fetch history for collaborating on dependency code.

These tools will all need to read and write the same file. It might be a good idea to require all tools to preserve the name and value of any fields they don't recognize. The PNG spec does this—a PNG processing tool must preserve unchanged any chunk with a type it doesn't know how to process. This is a powerful rule that allows the PNG format to be extended over time and experimented with, while letting old tools continue to work.

> To know how to interpret these fields the name of the tool must be known.

It seems tricky to put the name of "the" tool in the file when there might be multiple tools used. Maybe consider leaving it up to whatever tool is currently reading the file to define its own semantics for any fields not in the spec.

**Comment by kardianos** [comment]
You bring up a good point. The spec was originally written thinking a single tool would be used at a time. I think you're correct. The tool field should be removed and except for explicit user action, unknown fields should be preserved. This will have an effect on many fields where we are on the fence about.

**Comment by kr** [comment]
Nice! Thanks :D
