### ISSUE TITLE
Example 1, packages tls and context is incorrect

### ISSUE THREAD

**Issue by kardianos** [kardianos/vendor-spec#11]
Current vendor tool implementation and the spec differ on what the Vendor field should say. Take this package entry in Example 1:

```
{
    "Vendor": "github.com/coreos/etcd/internal/golang.org/x/net/context",
    "Local": "github.com/kardianos/mypkg/internal/golang.org/x/net/context",
    "Revision": "25f1feceb5e13da68a35ee552069f86d18d63fee",
    "RevisionTime": "2015-04-09T05:06:17Z-08:00"
}
```

It is shown here that the Vendor path is "github.com/coreos/etcd/internal/golang.org/x/net/context". However the vendor tool actually records a Vendor path of "golang.org/x/net/context". I think the tool is correct and the spec is wrong (and sufficiently precise).

At the same time I don't actually want to loose the fact that the files came from "etcd". I think this sounds like what @kr observed in issue #6 . Perhaps this would be the correct package entry:

```
{
    "Vendor": "golang.org/x/net/context",
    "AltURL": "github.com/coreos/etcd/internal/golang.org/x/net/context",
    "Local": "github.com/kardianos/mypkg/internal/golang.org/x/net/context",
    "Revision": "25f1feceb5e13da68a35ee552069f86d18d63fee",
    "RevisionTime": "2015-04-09T05:06:17Z-08:00"
}
```

**Comment by kr** [comment]
It's similar to what I was describing in #6.

It looks like etcd is now using a stock copy of x/net/context, but the commit in the description above, 25f1feceb5e13da68a35ee552069f86d18d63fee, doesn't appear in the history of https://github.com/golang/net. Supposing that coreos were maintaining a fork of x/net/context, I'd expect the AltURL in etcd to point to their fork (and to be a true URL):

##### etcd

```
{
    "Vendor": "golang.org/x/net/context",
    "AltURL": "https://github.com/coreos/net.git",
    "Local": "github.com/coreos/etcd/internal/golang.org/x/net/context",
    "Revision": "25f1feceb5e13da68a35ee552069f86d18d63fee",
    "RevisionTime": "2015-04-09T05:06:17Z-08:00"
}
```

Then it could be inherited by any project that depends on packages from the etcd repo:

##### mypkg

```
{
    "Vendor": "golang.org/x/net/context",
    "AltURL": "https://github.com/coreos/net.git",
    "Local": "github.com/kardianos/mypkg/internal/golang.org/x/net/context",
    "Revision": "25f1feceb5e13da68a35ee552069f86d18d63fee",
    "RevisionTime": "2015-04-09T05:06:17Z-08:00"
}
```

This lets everyone answer the question, "where is 25f1feceb5e13da68a35ee552069f86d18d63fee?"

**Comment by kardianos** [comment]
I think your right.

However, I couldn't guarantee that a tool (or even person) would always have the remote url. What do you think if the field was defined as prefer a remote url (tool can optionally enforce this) but an import path is also a valid value.

I'm inclined to name the field something different, maybe OriginURL or Origin, or SrcURL?

**Comment by kr** [comment]
If possible, I would suggest trying to keep things simple, which means avoiding things like "it can be X or Y". I think of the purpose of AltURL as, if the tool adding an entry to the package list knows that a patch isn't present in the upstream history, it can include the place where it is. Otherwise, if it doesn't know of an alternative URL, then it should just leave the field out.

I'm not sure I can think of a situation where a tool knows there should be something in the AltURL, but not also know what to actually put there. Do you have an example of this in mind?

**Comment by kardianos** [comment]
Kinda...
If I was to implement this in my "vendor" tool where I haven't taught it about vcs fetches, the source of the code and version is from the filesystem, specifically from a GOPATH path in the filesystem. So if I was to run "vendor update thepkg/foo" it would be able to say, OK, I won't try to fetch from the "Vendor" path, I'll look for it first in this alternate path. All without using a VCS.

But, I haven't implemented it, let alone used it to know it it is a true example.

**Comment by kr** [comment]
Understood, that makes sense. So it's an alternate import path where the current code might be found on the local disk (presumably already vendored inside some other project), as opposed to an alternate URL where the full history might be found.

Maybe separate fields would make sense for these two things, or maybe they should be combined into one. Or maybe the spec should define just one and not the other. Hmm.

**Comment by kardianos** [comment]
I don't have time to implement this right now, so I'll stick with a thought experiment:

### Field containing GOPATH
- Record the path relative to GOPATH it should copy files from if different from the Vendor field.
- Requires path to be present to update.

### Field containing repository URL
- Useful for tools that can fetch specific versions or update to the latest directly from a remote repo.
- If used with a go get meta header redirect, it could be discovered from a GOPATH.

### This applies to
- Import path rewrites
- Copy packages locally, but use GOPATH per project.
- No copy, only fetch packages, use GOPATH per project.

For non-"import path rewrite" solutions, this could be a local mirror, even while keeping the canonical vendor import path intact.

With the custom import path http://golang.org/cmd/go/#hdr-Remote_import_paths we could simply use that to translate to the actual repo urls. Then to tool could define when it used the local filesystem and when it would use the path to lookup the remote path.

@jingweno you might have a better opinion on this then I do as it looks like you've implemented updating from remotes. Thoughts? (See #6 as well.)

**Comment by owenthereal** [comment]
Hey guys, late for the party.

I'm gonna suggest something totally different but may solve #6  and update well :). How about changing the `vendor.json` format to:

``` json
{
    "Repo": "https://github.com/golang/net",
    "Revision": "25f1feceb5e13da68a35ee552069f86d18d63fee",
    "Local": "github.com/coreos/etcd/internal/golang.org/x/net",
    "RevisionTime": "2015-04-09T05:06:17Z-08:00"
}
```

`Repo` is the repo of the package, `Revision` is the revision to checkout, `Local` is the local vendored path (note that it's **not** import path). This resolves #6 well since it doesn't need to infer URL. It also solves update well:

```
$ git clone {Repo} tmp_repo
$ cd tmp_repo
$ git fetch && git checkout {NEW_VERSION}
$ rm -rf {Local} && cp -R tmp_repo {Local}
```

Last but not least, it doesn't have the awkwardness of expressing sub-packages from the same repo. For example:

``` json
{
    "Vendor": "golang.org/x/net/context",
    "Local": "github.com/kardianos/mypkg/internal/golang.org/x/net/context",
    "Revision": "25f1feceb5e13da68a35ee552069f86d18d63fee",
    "RevisionTime": "2015-04-09T05:06:17Z-08:00"
},
{
    "Vendor": "golang.org/x/net/html",
    "Local": "github.com/kardianos/mypkg/internal/golang.org/x/net/html",
    "Revision": "25f1feceb5e13da68a35ee552069f86d18d63fee",
    "RevisionTime": "2015-04-09T05:06:17Z-08:00"
}
```

Both packages are pointing to the same revision (because they're from the same repo). It will also cause minor headache to implement update where you have to find out both `golang.org/x/net/context` and `golang.org/x/net/html` are from the same repo and update both of them.

Just my two cents.

**Comment by kardianos** [comment]
@jingweno I think we need the "Vendor" field. Without the Vendor field it is difficult (impossible) to prevent duplicate packages. I think there is inherit awkwardness of the repository vs package. It is also critical that each entry represent a package, not a package tree. This file isn't just for humans, this files is primarily for machines. Also it is entirely possible that the context package is updated to a newer version and html is left as is, even though they originate from the same repository.

Let me know if what I'm saying doesn't sound accurate.

I think we need two fields: Origin and URL. Origin will denote the path relative to GOPATH, and URL will denote the remote repository url. A tool could use the url exclusively.  It could also attempt to resolve the URL automatically from hitting the Origin and looking for the head tag (what go get does).

**Comment by owenthereal** [comment]
> I think we need the "Vendor" field. Without the Vendor field it is difficult (impossible) to prevent duplicate packages.

Why do you need to prevent duplicate packages in `vendor.json`? I don't think I see a direct answer.

> Also it is entirely possible that the context package is updated to a newer version and html is left as is, even though they originate from the same repository.

I'm not sure I buy into this argument either. What you're saying is the code wants a newer version of a subpackage and it also wants the rest of the subpackages the same. First of all, only "similar" packages should be bundled into the same repo. If there's a case that some subpackages are changed and break the rest of the subpackages, maybe the library author should split this breaking subpackage into another repo. Or maybe the author shouldn't even do that to maintain stability of the APIs.

**Comment by kardianos** [comment]
I view it to be a hard requirement to prevent duplicate packages. I also view it as a hard requirement to support vendoring packages that also vendor packages. Despite not being optimal, it has come up in practice more then once and must be caught.

Regarding packages being on different versions within the same repo, I agree that it doesn't make sense in most cases. However, tools need a way to express what the user does. If a user chooses to update one package in a repo and leaves the other, I would leave that up to the user. If a tool wants to enforce all packages in a repo use the same version, I'd like to put that on the tool, not the spec.

Are these issues you can bend on, even if you don't entirely agree?

**Comment by owenthereal** [comment]
> Despite not being optimal, it has come up in practice more then once and must be caught.

Can you give a concrete example that proves this is indeed an issue rather than saying it's a hard requirement? What's the problem are you trying to solve?

> However, tools need a way to express what the user does. If a user chooses to update one package in a repo and leaves the other, I would leave that up to the user.

But the thing is the responsibility is on the library authors to break packages into repos that make sense. The users wouldn't need to update one subpackage and not the rest of them. If they want to, just update the repo directly.

> Are these issues you can bend on, even if you don't entirely agree?

I'm afraid I can't bend on this. Because the spec doesn't work with what I'm trying to do with [nut](https://github.com/jingweno/nut). For `nut`, I would want users to define the repo and the version of the packages that they want to depend on, e.g.,

``` toml
[dependencies]
"https://github.com/golang/net" = "25f1feceb5e13da68a35ee552069f86d18d63fee"
```

And `nut` will download the package with that particular version and users can import the package/subpackages however they want. That being said, `nut` won't be able to know the import paths of the code. Hope it makes sense.

**Comment by kardianos** [comment]
I think this could work with nut. You would probably either need to augment the vendor.json file with a repo object that listed repo with hash or still have an external file. The tool could then take write the package files used so other tools could still talk. Tools are explicitly allowed to extend the vendor file. The vendor file spec is just the required fields, and the definitions of some optional fields that can be used to communicate where packages are regardless of the tool.

Sure, I can give an example. cockroachdb needs to import coreos/ectd/raft. raft uses the imported package golang.org/x/net/context. cockroachdb also uses context. When cockroachdb vendors raft and context, it should ensure only a single import of the canonical import path context, even though raft re-writes its imports.

**Comment by owenthereal** [comment]
> The vendor file spec is just the required fields, and the definitions of some optional fields that can be used to communicate where packages are regardless of the tool.

Other tools won't be able to accept the `vendor.json` written by `nut` since it doesn't write out vendor import path and local import path because it doesn't know anything about import paths. If these two fields are mandatory, then `nut` is not even compatible with the spec...

> cockroachdb needs to import coreos/ectd/raft. raft uses the imported package golang.org/x/net/context. cockroachdb also uses context. When cockroachdb vendors raft and context, it should ensure only a single import of the canonical import path context, even though raft re-writes its imports.

I still don't get how your proposal solves this...could you point me to the code? That will make the discussion more productive and reflect more a real world example. However, it sounds like a very typical dependency management issues - to resolve two versions of a dependency.

**Comment by kardianos** [comment]
Yes, I have a tool that reads the current project vendor file and looks at dependency vendor files at: github.com/kardianos/vendor .

This is a matter of arity. nut's arity is per repository, the spec arity (and one tool that currently uses) is per package. Because multiple packages can be in a single repository, the "per package" will always contain the information that "per repo" will contain. Think of it like a SQL group by.

Please do try out how the github.com/kardianos/vendor tool works. It certainly isn't the only way to vendor packages by any means, but I hope it can demonstrate the necessity of recording per package.

If you continue to object to per package arity, go ahead and open a dedicated issue to that.

**Comment by owenthereal** [comment]
> Yes, I have a tool that reads the current project vendor file and looks at dependency vendor files at: github.com/kardianos/vendor

Sorry if I wasn't clear. I was expecting you to have the code that demonstrates the problems of cockroachdb & raft depending on different versions of `golang.org/x/net/context` and how your definitions of the spec solves this problem, in echo to your point of "prevent duplicate packages".

> This is a matter of arity. nut's arity is per repository, the spec arity (and one tool that currently uses) is per package. Because multiple packages can be in a single repository, the "per package" will always contain the information that "per repo" will contain. Think of it like a SQL group by.

I don't think it's a problem of "group by" or not. It's a problem that `nut` isn't able to satisfy the spec if it stays as is. I have done some writeup on `nut`'s mission: https://github.com/kardianos/vendor-spec/issues/14.
