### ISSUE TITLE
Vendor spec from `nut`'s perspective

### ISSUE THREAD

**Issue by owenthereal** [kardianos/vendor-spec#14]
I'm trying to lay down what [nut](https://github.com/jingweno/nut) is trying to do and let's see if we could agree on a minimum spec that works for `nut` and other vendoring tools.

`nut` is an opinionated vendoring tool that advocates declaring dependencies on a manifest file (`Nut.toml`) and vendoring dependencies by rewriting import paths.

Given a manifest file `Nut.toml` in the project root:

``` toml
[dependencies]

"github.com/codegangsta/cli" = "25f1feceb5e13da68a35ee552069f86d18d63fee"
```

with package **repository URL** as the key and **commit-ish** as the value, running `nut install` will download the package `github.com/codegangsta/cli` to `PROJECT_ROOT/internal/github.com/codegangsta/cli`. It also downloads `github.com/codegangsta/cli`'s dependency `golang.org/x/tools` to `PROJECT_ROOT/internal/golang.org/x/tools`. `nut` then rewrite import paths of all dependencies and write to a `vendor.json` so that other vendoring tools may consume it. Note that up to this stage, `nut` **doesn't know anything about import paths**. The `vendor.json` may look like this:

``` json
{
  "Repo": "https://github.com/codegangsta/cli",
  "Local": "github.com/coreos/etcd/internal/github.com/codegangsta/cli",
  "Revision": "25f1feceb5e13da68a35ee552069f86d18d63fee"
},
{
  "Repo": "https://go.googlesource.com/tools",
  "Local": "github.com/coreos/etcd/internal/golang.org/x/tools",
  "Revision": "8568b34ba04ac5e1259cdb2d916c14def1bb4273"
}
```

So I'm proposing the vendor spec to have fields "Repo", "Local" and "Revision". "Repo" is the repo of the package (it could be multiple subpackages, but users never define subpackages in `Nut.toml`), "Local" is the local path of the **repo**, "Revision" is the revision of the repo.

**Comment by jbuberel** [comment]
Let's consider a vendoring tool that prefers an external vendoring approach, like `gb-vendor` (Dave Cheney's vendoring plugin to the `gb` tool). 

His `gb vendor` will place those files into:

```
project_root_dir/
    src/
    bin/
    vendor/src/
        github.com/codegangsta/cli
```

Would the configuration for that placement look like this:

```
{
  "Repo": "https://github.com/codegangsta/cli",
  "Local": "vendor/src/github.com/codegangsta/cli",
  "Revision": "25f1feceb5e13da68a35ee552069f86d18d63fee"
},
```

Does that look right to you?

**Comment by owenthereal** [comment]
@jbuberel Yes, assuming "Local" is the relative path of the repo to project root. If ignoring the project root segments, my above examples can be simplified as:

``` json
{
  "Repo": "https://github.com/codegangsta/cli",
  "Local": "internal/github.com/codegangsta/cli",
  "Revision": "25f1feceb5e13da68a35ee552069f86d18d63fee"
},
{
  "Repo": "https://go.googlesource.com/tools",
  "Local": "internal/golang.org/x/tools",
  "Revision": "8568b34ba04ac5e1259cdb2d916c14def1bb4273"
}
```

/cc @davecheney @kr @kardianos

**Comment by davecheney** [comment]
@jbuberel gb does not require a configuration file, if there must be such a file, it will live in `$PROJECT/vendor` hence the "local" destination will always match the location where the code is placed.

**Comment by kardianos** [comment]
@jingweno Would you be willing to close this issue out?

**Comment by owenthereal** [comment]
Closing.
