### ISSUE TITLE
spec: Local field is redundant

### ISSUE THREAD

**Issue by davecheney** [kardianos/vendor-spec#15]
The spec defines two fields

```
        // Vendor import path. Example "rsc.io/pdf".
        // go get <Vendor> should fetch the remote vendor package.
        Vendor string `json:"vendor"`

        // Package path as found in GOPATH.
        // Examples: "path/to/mypkg/internal/rsc.io/pdf".
        //
        // Local should always use forward slashes and must not contain the
        // path elements "." or "..".
        Local string `json:"local"`
```

it also states

> The vendor file will be in the "internal" folder and be called "vendor.json".
> it seems to me that the value of `Local` can always be deduced as the current working directory of the `vendor.json` file plus the contents of `Vendor`. 

Can `Local` be removed from the spec ?

**Comment by kardianos** [comment]
That depends on how much restriction you want to place on tools. For
instance I could see a tool choosing to put the rewritten imports under
different paths. For instance "golang.org/x/net/context" could be placed in
"$PROJ/internal/v/context"` or in "$GOPATH/src/company/third_party/context".

I would prefer to keep this flexibility and keep the field.

**Comment by davecheney** [comment]
Whoa. That's a free for all, what possible purpose could this level of flexibility serve except all accidental duplicates of packages in the final binary?

Very stopping objection to anything but a straight one to one translation of remote path to locally censored path,

**Comment by kardianos** [comment]
Field "local" is required.
