### ISSUE TITLE
spec: non canonical fields should be required to have a `x-` prefix

### ISSUE THREAD

**Issue by davecheney** [kardianos/vendor-spec#16]
The spec suggests that additional fields may be present in the `vendor.json` file, and that those fields should be unmolested by tools that do not understand them.

For forward compatibility I suggest that these non canonical fields be identified with a prefix of `x-` to avoid conflict with future versions of the specification that may choose to canonicalise them.

**Comment by kardianos** [comment]
This is a good point and has precedence. The counter point I would make is
that should a future version canonicalise them it will likely take the
fields that tools use, thus adding a need for future version to un "x-"
them. I'm not sure which precedence I should take example here: the HTTP
X-HEADER example (good) or the css "webkit-foo" example (bad). My initial
response is this is closer to the css precedence.

I'd be willing to merge such a change in, but it would need support of
others too.

**Comment by davecheney** [comment]
That's why you need a schema version.

**Comment by owenthereal** [comment]
:+1:

**Comment by kr** [comment]
I disagree. Note that the IETF recommends _against_ using any prefix, such as `X-` or `webkit-`, for nonstandard fields.

https://tools.ietf.org/html/rfc6648

This vendor spec is a clear-cut example of just the sort of situation described in RFC 6648. We should take those lessons to heart here, and encourage vendoring tools not to use any sort of special naming convention for their extension fields as distinct from standardized fields.
