### ISSUE TITLE
spec: Schema version required

### ISSUE THREAD

**Issue by davecheney** [kardianos/vendor-spec#17]
For forwards compatibility the spec should define a top level field, 
<pre>Schema int 'json:schema'  // should be back ticks, but markdown won't permit that</pre> which identifies the version of the schema the `vendor.json` file should be interpreted with.

**Comment by kardianos** [comment]
I'm open to this, though if possible in the future I would like to just
assign a default meaning to fields that are not present. Of if there is a
revision in the future we could add this and the default version would be
the initial version.

**Comment by davecheney** [comment]
What if you need to remove a field in the future? You really need to version your scheme so you can say what is mandatory and what is no longer permitted.

**Comment by kardianos** [comment]
If a field is removed then I suppose it would just be ignored. But again,
I'm open to this suggestion. I want feedback from others before adding
though.

**Comment by owenthereal** [comment]
Versioning the spec makes sense. It would help us evolve the spec.

**Comment by kardianos** [comment]
A version may be introduced in the future. However for now it will be omitted. 

If a version number is needed in the future an omitted version will be assumed the first version.

**Comment by davecheney** [comment]
This is a serious omission. I hope you will reconsider adding a version
identifier.

On Sat, May 23, 2015 at 3:35 AM, Daniel Theophanes <notifications@github.com
