### ISSUE TITLE
Change name of Vendor field

### ISSUE THREAD

**Issue by jbuberel** [kardianos/vendor-spec#18]
Another request from the Go team - change the name of the vendor field, because it is confusing.

The concern is that users will assume that the 'vendor' field is used to capture where the vendored code has been stored. That value is stored in 'local', of course.

Perhaps: 'remote' or 'source' or 'origin'?

**Comment by kardianos** [comment]
Sure.
What about "canonical"? I'm not thrilled about "remote" or "origin" but I'm alright with "source".

**Comment by jbuberel** [comment]
I like canonical, and I agree that 'source' would be reasonable too.

Your call.

Jason L. Buberel
jason@buberel.org
