### ISSUE TITLE
reconsider using Go-style uppercase field name capitalization

### ISSUE THREAD

**Issue by kr** [kardianos/vendor-spec#19]
Commit 04961d8919354ec2a27b593050543a5b70ea6008 changed field names to use json tags for lower-case output.

I think that change should be reconsidered. IMO the go tool's JSON output is a more relevant precedent here than various style guides on the internet. Since the go tool doesn't use json tags and uses Go-style field name capitalization, I think this spec should do so as well.

As a practical matter, I'd wager most tools that produce this format will be written in Go. It seems silly to make all of them include noisy json tags in their type definitions just so that all the other tools, also written in Go, will have to translate from the lower case names back to upper-case struct fields using more json tags.

**Comment by kardianos** [comment]
@kr I agree, but I'm willing to defer to the Go team. This particular request was from them. Perhaps @jbuberel can give feedback how strong this request was.

**Comment by jbuberel** [comment]
Both Brad Fitzpatrick and Russ Cox requested that the JSON spec be more
"JSON-like" (using lower-case names) instead. I don't personally have a
strong opinion, so I was primarily representing their request/feedback.

Jason L. Buberel
jason@buberel.org

On Tue, May 19, 2015 at 3:15 PM, Daniel Theophanes <notifications@github.com

**Comment by kr** [comment]
Okay.
