### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by ngrilly** [kardianos/vendor-spec#2]
Thanks for having written this vendor file specification!

Two questions:
- Some people recommend to use one GOPATH per project and to commit the whole GOPATH in your VCS. This seems especially popular in companies that use a single company-wide source code repository (like at Google and Facebook). Another reason is that most people already run one virtual machine per project (using Vagrant, Docker, etc…) which makes it easy to use one GOPATH per project (in the virtual machine). What is your opinion/experience on this?
- What is your workflow when you change a "vendored" package? Do you work on the original version stored in your GOPATH (before import path rewriting) or on the "vendored" version stored in internal? If you work on the original version, do you execute `vendor update` after each change before executing `go build/run`? In your experience, does import path rewriting make more difficult to share code with upstream?

**Comment by kardianos** [comment]
1. At google, they commit the whole GOPATH, but it isn't per project. The single GOPATH serves all projects. Updates happen to the entire tree.
2. Some people do run one GOPATH per project. That's probably fine, I think that is fine so long as the dependencies are checked in somewhere. I think it is unnecessary. Just use a tool like "vendor" and rewrite the import paths at that point.
3. If I want to update a vendor package to a repo that has been re-written, there are two options:
   - run "vendor remove vendor/pkg/path",run "go get -u vendor/pkg/path", check for breaks, etc... then when I'm happy run "vendor add vendor/pkg/path".
   - run "vendor update vendor/pkg/path", adjust code for any break, test.
4. In my experience import path rewriting makes it easier. Main packages just work. No extra legwork required by the user. If another user wants to share code with another project, the vendor file is used to de-duplicate any code and choose a sane package structure. I've tried this with some of my packages, and it just works. Providing the vendor file is established, tools should be able to cope.

**Comment by ngrilly** [comment]
> 1. At google, they commit the whole GOPATH, but it isn't per project.

You're right: my comment was confusing two orthogonal decisions: a) use the same GOPATH for all projects or one GOPATH per project and b) use a single company-wide repository or one repository per project.

> 1. Some people do run one GOPATH per project. That's probably fine, I think that is fine so long as the dependencies are checked in somewhere. I think it is unnecessary.

I'm not sure that I understand. What do you mean by "unnecessary"? Do you mean it's "fine" (because "dependencies are checked in somewhere") but "overkill" (because you think that rewriting import path is simpler than managing one GOPATH per project)?

> 1. If I want to update a vendor package [...]

In practice, do you tend to use the first solution when the change is complex and/or requires many commits, and use the second solution when the change is simple and requires only one commit?

> 1. [...] If another user wants to share code with another project, the vendor file is used to de-duplicate any code and choose a sane package structure.  [...]

I fully agree. I think this is the most interesting part of your approach, compared to previous solutions. It solves a significant issue with vendoring, by making it easy to vendor a project that itself uses vendored dependencies. The usefulness of storing Vendor and Local attributes in the vendor file cannot be understated.

Does it mean that your tool (vendor) can be used for both applications (where vendoring is usually the preferred approach in Go) **and** libraries (where vendoring is usually avoided)?

One last thing: I appreciate the idea of import path rewriting but I'm still bothered by the idea of "changing" the source code of a dependency, instead of just vendoring it without any change. Basically, I have to choose between the burden of having to manage one GOPATH per project and the burden of import path rewriting. Any last word on this? ;-)

**Comment by ngrilly** [comment]
> 1. If I want to update a vendor package to a repo that has been re-written, there are two options:

I'm thinking of a third workflow: directly edit the vendored dependency in internal/vendor/pkg/path, test, and when the code is ready run something like "vendor backport vendor/pkg/path" that rewrite the import path to their original form and write the result in $GOPATH/src/vendor/pkg/path. In other words, "vendor backport" is the inverse of "vendor update".

**Comment by kardianos** [comment]
I kinda like that idea. Nice. Feel free to open an issue for that.

**Comment by kardianos** [comment]
On Tue, Apr 21, 2015 at 10:58 AM Nicolas Grilly notifications@github.com
wrote:

> 1. At google, they commit the whole GOPATH, but it isn't per project.
>    
>    You're right: my comment was confusing two orthogonal decisions: a) use
>    the same GOPATH for all projects or one GOPATH per project and b) use a
>    single company-wide repository or one repository per project.
> 2. Some people do run one GOPATH per project. That's probably fine, I
>    think that is fine so long as the dependencies are checked in somewhere. I
>    think it is unnecessary.
>    
>    I'm not sure that I understand. What do you mean by "unnecessary"? Do
>    you mean it's "fine" (because "dependencies are checked in somewhere") but
>    "overkill" (because you think that rewriting import path is simpler than
>    managing one GOPATH per project)?
> 
> Yes. That is what I mean. :)
> 1. If I want to update a vendor package [...]
>    
>    In practice, do you tend to use the first solution when the change is
>    complex and/or requires many commits, and use the second solution when the
>    change is simple and requires only one commit?
> 
> I think it would more depend on where the vendor code is coming from. Have
> you used it before...
> 1. [...] If another user wants to share code with another project, the
>    vendor file is used to de-duplicate any code and choose a sane package
>    structure. [...]
>    
>    I fully agree. I think this is the most interesting part of your
>    approach, compared to previous solutions. It solves a significant issue
>    with vendoring, by making it easy to vendor a project that itself uses
>    vendored dependencies. The usefulness of storing Vendor and Local
>    attributes in the vendor file cannot be understated.
> 
> Does it mean that your tool (vendor) can be used for both applications
> (where vendoring is usually the preferred approach in Go) _and_ libraries
> (where vendoring is usually avoided)?

The vendor tool _can_ be used for libraries, but I still would normally
avoid it in most cases (though not in all, such as a dependency to a
library that is known to move the API around lots).

> One last thing: I appreciate the idea of import path rewriting but I'm
> still bothered by the idea of "changing" the source code of a dependency,
> instead of just vendoring it without any change. Basically, I have to
> choose between the burden of having to manage one GOPATH per project and
> the burden of import path rewriting. Any last word on this? ;-)

gofmt
goimports

They fully re-write your files, "changing them" every time you use them.

The vendor tool uses the exact same method as gofmt, and a much less
invasive method then goimports. goimports actually removes imports and
_guesses_ new imports. Eeep! The vendor tool only changes it to known good
import paths that are mechanically known to be correct.

-Daniel
