### ISSUE TITLE
Update examples to use GO15VENDOREXPERIMENT

### ISSUE THREAD

**Issue by nathany** [kardianos/vendor-spec#22]
Thanks for this Daniel. 

Not sure if you were following this recent addition to Go 1.5:

cmd/go: add preliminary support for vendor directories (GO15VENDOREXPERIMENT=1)
https://go-review.googlesource.com/#/c/10923/

Which means import paths wouldn't need to contain `github.com/kardianos/mypkg/vendor/`(and in fact, would not be allowed to contain a vendor path when that flag is set)

**Comment by kardianos** [comment]
Hi @nathany , I am indeed keenly aware of the recent events. I'm hoping to continue to work with Jason, Keith, and others to modify this if needed. We haven't had time to fully discuss the ramifications yet.

**Comment by kardianos** [comment]
@nathany I will update the examples soon. I'm currently working on adding support for GO15VENDOREXPERIMENT to kardianos/vendor tool. Once initial support is landed, either on a branch or in master I'll update the text and examples. Thanks!

**Comment by nathany** [comment]
:+1:

**Comment by kardianos** [comment]
@nathany I think the only thing that needs to change is the following:
https://github.com/kardianos/vendor-spec/commit/8a2944ec130d5706db2bf496420c7303adbcded6

If you agree I can merge the branch.

While the spec would typically point to the vendor folder, nothing stops you from pointing to arbitrary packages, rewritten into internal or other places.

**Comment by nathany** [comment]
LGTM. Thanks.
