### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by nathany** [kardianos/vendor-spec#23]
> Copying third-party vendor packages into a local project structure requires a meta-data file describing the vendor's packages.

I don't think this is actually true. The code is all there, metadata isn't required. But it could certainly be beneficial. The later bullet points give some benefits:

> prevent duplicate packages from being included and store the revision of a package.

**Comment by kardianos** [comment]
@nathany When this was to support vendor rewrites, that was very much true. We still haven't decided how to pivot this to support recording versions.

The vendor package is still an experiment, so while I want to support it, in the mean time I don't want to burn my bridge for rewrites.

**Comment by kardianos** [comment]
@nathany Recent update fixes this.
