### ISSUE TITLE
don't call it a vendor file

### ISSUE THREAD

**Issue by thisguycodes** [kardianos/vendor-spec#24]
Pinning/identifying precise dependencies and their versions is incredibly important, and I generally agree with taking very opinionated approaches when designing things, but is there actually any advantage to tying this so tightly to the idea of vendoring your code? Could we not call it `deps.json`, with all the same fields, and allow vendoring tools to use it in that way?

Personally I do not like vendoring code. I understand the advantages and I like how people are making a decision and moving forward with it, but I could personally use this exact same spec (as it stands) to pull dependencies instead of vendoring them. I don't see a reason to name it so specifically.

**Comment by kardianos** [comment]
"vendor" is a word.
In context one might say, "Let's go talk to the food vendors" or "We have a
meeting with the widget vendor".

"vendor" packages are packages a different organization wrote.
Whether you copy them locally or fetch them at build time is another matter.

**Comment by thisguycodes** [comment]
This is a fair response
