### ISSUE TITLE
only support tags, not revision pointers

### ISSUE THREAD

**Issue by thisguycodes** [kardianos/vendor-spec#25]
I don't 100% know how these things with with not-git, but hear me out.

Because Go does not have (and doesn't appear to be developing) a concept of a package manager, and is instead going for package vendoring with per-repository version dependencies, I foresee a serious issue around dependency versions with diamond dependencies. This is amplified by the fact that existing tools (and this spec) seem to be encouraging pointing at specific commits.

I propose that this specification only support tags, not individual revisions. This will encourage _some_ level of convergence with dependencies (more specifically discourage depending on random commits), and even better encourage package maintainers to actually _have_ releases. And even when specific patches are needed between releases (cause bugs that break you happen), it can be worked around by forking and doing your own release tag.

Optionally this could be taken further by enforcing a certain tag type (ie: semver, vX[.Y[.Z[-xxx]]]), which would encourage/force package maintainers to let people more easily use services like `gopkg.in` to make version dependancies more explicit. This is a bit more extreme though.

I want to start this conversation, because the idea of growing disparity around dependency paths is really starting to concern me. Even more so with the movement towards vendoring instead of a package manager.

**Comment by kardianos** [comment]
In Go we don't have a central code storage and tagging thing.

Rather each developer decides what the canonical path should be. If you own a domain you can put in meta tags that allows you to redirect to a source control location. You can also decide to put it behind a tagging service like "gopkg.in". You can also enforce the canonical path by using the import comment.

If the vendor-spec is ultimately used and adopted, it will allow tools like "go get" to fetch packages into the "vendor" folder at a specific revision.

If I understand you correctly, you want to be able to also specify a semantic version that is tagged by some means and not tied to a specific version (to support bug fixes and other uses).

I am fine with a tool adding a "version" field that in more of a semantic version. Then a vendor tool could "bump" the revision when a user wants to. Currently the spec includes the verbage:

```
A tool MUST persist any unknown fields when reading and
writing out the vendor file. A tool may remove unknown fields
on an explicit user request. This implies that a tool must not
marshal or unmarshal from a known struct.
```

---

What do you currently do to handle dependencies right now? Do you have a desire to work on a vendor tool to enable the above workflow?

**Comment by thisguycodes** [comment]
The enforcing any idea of semantic versioning was entirely a secondary point. The problem I'm looking to prevent is several packages depending on whatever the latest `master` was at the time that they did `go get` (which is all too common right now), and any amount of tooling being unable to determine what a safe resolution path is for diamond dependencies. By enforcing a 'release' concept we could seriously alleviate this, at the very least by drastically reducing the number of versions one _could_ depend on (only things that are tagged), if we also enforced something like semver then we'd be creating a path for tools to provide dependency resolution (and avoid including several copies of the same library in an executable)

**Comment by kardianos** [comment]
@conslo Then I'm not sure what the issue is with the vendor spec. If the vendor spec was used by "go get" and other vendor tools, would you see a problem? If so, what would the problem be?

**Comment by thisguycodes** [comment]
I suppose this problem can be a bit hard to communicate, but it's very real (and one I already deal with). Give me a bit and I'll draw some pictures (as it's easier to illustrate than type).

**Comment by thisguycodes** [comment]
![image](https://cloud.githubusercontent.com/assets/450860/8387074/b7783d80-1c0a-11e5-87e5-544b74ebfa33.png)
Which version of the mysql driver should a vendor tool decide to keep? Or how could it make this decision? Or how could it even phrase the question to a user in a way that would actually allow them to make an intelligent decision?

With this idea, I'm not proposing to eliminate this problem, but to _constrain_ it.
![image](https://cloud.githubusercontent.com/assets/450860/8387147/229464d6-1c0b-11e5-9686-72efe9d1eafc.png)
There are 564 possible commits that, given the current spec, a vendor file could point at. But only 9 releases (tags). Restricting users to using only tags would drastically increase the likelihood that two dependencies use the same version, as well as let tools ask more intelligible questions:
`Use a: "Version 1.2" or b: "Version 1.1" of "github.com/go-sql-driver/mysql"?:`

If my secondary suggestion was also taken (restricting tags to semver-like names), we'd be creating a path for vendor tools to do auto-resolution (use later minor-version but same major version, or detect incompatible combinations, etc).

Perhaps it'd also be prudent to allow libraries to state when a dependency does not have 'side-effects' and thus can be included as a second copy (this is a bit iffy, and I don't know if I want to encourage it, but it has an argument). This could also simply be implemented by independent tools and since preserving other fields is a requirement may not need to be in this spec.

Implementing a restriction like this is a very opinionated approach. But I feel it's incredibly pragmatic, and would help alleviate a lot of issues down the line.

**Comment by thisguycodes** [comment]
@kardianos thoughts? I could compare this to the explicit publishing process people go through for publishing python/Ruby/bower/npm packages. A key difference here is we're not building a package manager, but I do see this spec as one of the decisions that needs to be made of that's ever desired, so I want to consider things like this as much as possible.

**Comment by kardianos** [comment]
@conslo What you are describing is a "diamond dependency" where the common dependency is specified to different revisions. A tool would be free to have this restriction. This won't be a restriction at the spec level. At the end of the day a version is not specific enough. A version like 1.4 could point to the 1.4.1 revision or 1.4.2 revision. And some people keep the exact same version but apply it to a different revision. A revision is necessary, even if a version is also used or required by a tool.

**Comment by thisguycodes** [comment]
@kardianos I'm aware that it's called a diamond dependency.

And I specified "tags" and not "versions", this was very deliberate.

Versions are non-specific as you describe, but tags point to one, and _only_ one, revision. The purpose of my proposal was to require package maintainers to actually declare "I find this revision suitable for release" by creating a tag, and require people creating dependency trees to actually decide on a revision rather than just "whatever master happened to point to when I pulled".

I was seeking a debate as to the pro's and cons of adding this restriction at the spec level, not a "yes" or "no" answer.

**Comment by kardianos** [comment]
Fair enough.

In non-git systems, I know tags can be moved. Practically speaking I'm not sure what the difference is (though I know the difference in git).

There is only one and only one revision, and in git but not mercurial there is only one tag that cannot be moved. Many packages never issue a tag or official release. Should those not be eligible for pinning?
