### ISSUE TITLE
Reasoning behind required RevisionTime field

### ISSUE THREAD

**Issue by thisguycodes** [kardianos/vendor-spec#26]
`If the Revision field is non-empty the RevisionTime field must correlate with the Revision field.`

What is the reasoning behind this requirement? While if I have a revision (and a copy of the repository it is from) I should always be able to obtain the information needed for the RevisionTime field, is it necessary? When I pull a repository by hand the only information I need is the tag/revision I want checked out. I can't actually think of a use case for this field at all, though I'm sure it was put there for a reason.

**Comment by kardianos** [comment]
Have you done maintenance programming on a code base older then 7 or 10 years old? In my experience when working on an older code base time is really handy. This field isn't for a machine, it is for people. When a maintenance programmer opens up this file 10 or 20 years from now, I want them to know approximately "when" a package has last seen an update.

For instance, if I had a security related package that I noticed hadn't been updated in the last 5 years I might want to take a look at that package. It would also be useful if the package has switched version control systems and no longer contains a reference to the hash.

You are correct that it isn't strictly necessary.

**Comment by thisguycodes** [comment]
I have not done maintenance like that before. But that seems like a very real problem, and I actually like requiring that field at the spec level to solve it. Thanks for the explanation.
