### ISSUE TITLE
allow/encourage placing vendor.json in vendor directory (not above it)

### ISSUE THREAD

**Issue by rsc** [kardianos/vendor-spec#28]
The examples on the front page assume that you create vendor.json in the parent of the vendor directory. It seems to me more useful to put it inside the vendor directory, so that all the vendored data is together in one rooted tree and can be copied, moved, diffed, etc together. If vendor.json is in the parent of the vendor directory then there is no such coherent root. 

Placing vendor.json in the vendor directory also makes canonical and local usually the same string, which is nicer. Perhaps one can be elided by default (I will file a separate bug for that).

I have been creating vendor.json files for the manual vendoring I've been doing in the main Go repo and the golang.org/x/arch subrepo, and I have been placing them in the vendor directory.

**Comment by kardianos** [comment]
Given the other issues raised, there is a strong case to specify where it goes. I'll update to require placement into /vendor/.
