### ISSUE TITLE
do not require both canonical and local

### ISSUE THREAD

**Issue by rsc** [kardianos/vendor-spec#29]
In #28 I suggested allowing/encouraging vendor.json to be placed in the vendor/ directory by convention. 

If you do that, then a vendor.json might look like:

```
{
    "package": [
        "canonical": "golang.org/x/arch/x86/x86asm",
        "local": "golang.org/x/arch/x86/x86asm",
        "revision": "ad6a463afcf9bd5b38c81fa9ba612dae11859d40",
        "revisionTime": "2015-08-28T15:42:14Z"
    ],
    "package": [
        "canonical": "golang.org/x/arch/arm/armasm",
        "local": "golang.org/x/arch/arm/armasm",
        "revision": "ad6a463afcf9bd5b38c81fa9ba612dae11859d40",
        "revisionTime": "2015-08-28T15:42:14Z"
    ]   
}
```

or

```
{
    "package": [
        "canonical": "rsc.io/pdf",
        "local": "rsc.io/pdf",
        "revision": "371ad118eb63f9f52971201c4e903420401ed37f",
        "revisionTime": "2015-07-23T06:11:39Z"
    ]
}
```

(I wrote these by hand; maybe there are mistakes.)

It seems redundant to have to write both "canonical" and "local" when by convention they should almost always be the same. I understand that there will be cases where they differ and so that must be expressible, but that exceptional case should not complicate the common case.

It seems like one of these two should be made optional; when omitted it should take the same value as the required one.

**Comment by ascarter** [comment]
+1. It seems way more idiomatic to default to the convention and only need these for exceptions.

**Comment by kardianos** [comment]
I'm totally fine with this. In order to do this we need to:
1) require "vendor.json" be in the "vendor" folder or change the path requirements.
2) require "vendor.json" to only represent the first layer in any nested vendor tree.

Both this issue's suggestion and the above two requirements appear to be sane and valid simplifications. How would you prefer to resolve (1)? Require the location of "vendor.json" to be fixed or make some other pathing requirement?

**Comment by rsc** [comment]
Re 1) I'm not sure what you mean by change the path requirements, but I would say vendor.json should be in the vendor folder (see #28).

Re 2) Yes, an inner vendor directory should have its own vendor.json. (Of course vendor.json represents only what it contains entries for. The outer vendor.json would be convention not contain entries mentioning the inner vendor subtree.)

**Comment by kardianos** [comment]
I'll update the examples shortly and update the wording to reflect this explicitly.
