### ISSUE TITLE
Spec should include a way to describe the tool used to generate the file

### ISSUE THREAD

**Issue by freeformz** [kardianos/vendor-spec#38]
My use cases:
1. As a consumer of a code base that includes a vendor.json I would like to know which tool generated the file and where to check for bugs / fixes / etc in that tool should the need arise.
2. As a service that would like to track the tooling used by it's developer-users, so that it can understand the tooling they use and better support them.

**Comment by kardianos** [comment]
A "Tool" field was actually in the initial draft: https://github.com/kardianos/vendor-spec/commit/9840aeeed9009d9eff24552466a7ef5050365cb7

I'm personally open to adding it back in. Let me lookup when it went away any why thought.

**Comment by kardianos** [comment]
@freeformz I think this is reasonable, especially if we state:
1. It is optional.
2. It is for tools; hand written (or internal scripts) don't need to to write it.
3. Tools can disable writing to this field if the user want it to.

That being said, I'd like to leave this as an open issue for now until at least one other tool supports the spec.
