### ISSUE TITLE
Consider adding a 'Comment' field to the package struct?

### ISSUE THREAD

**Issue by jbuberel** [kardianos/vendor-spec#4]
Given the lack of commenting support in JSON, do you think it makes sense to add a Comment field ("comment" in the JSON) of type string to allow for ~ free form text comments. It would be nice to be able to:

description: "We are using this revision because all later releases introduced bug XYZ that we want to avoid."

**Comment by kardianos** [comment]
That sounds good to me. Perhaps both at a package level and at a file level, as the comment at the file level won't disappear.
