### ISSUE TITLE
spec: Package.Version should be Package.Revision

### ISSUE THREAD

**Issue by davecheney** [kardianos/vendor-spec#5]
From the proposed spec

```
        // The version of the package. This field must be persisted by all
        // tools, but not all tools will interpret this field.
        // The value of Version should be a single value that can be used
        // to fetch the same or similar version.
        // Examples: "abc104...438ade0", "v1.3.5"
        Version string
```

I believe this is incorrect. 

Go packages do not currently have versions, at least not in the way that npm packages, cpan modules, maven jars, or python eggs, have versions.

Go packages may live in source control and that source control system may defined a _revision_ which identifies the particular copy of the source of that package at a point in time -- which is what this field is capturing.

I'm not saying that Go packages shouldn't have versions, but I am certain that they don't have a version at the moment and the spec should instead capture the _revision_.

/cc @kardianos @jbuberel

**Comment by kardianos** [comment]
Fixed with https://github.com/kardianos/vendor-spec/commit/ac977aaa060d1aec6cea6102c855a429bae58e13 .

**Comment by davecheney** [comment]
Well, that was easy :)
