### ISSUE TITLE
consider providing an alternate history URL

### ISSUE THREAD

**Issue by kr** [kardianos/vendor-spec#6]
Here is a problem that has emerged after some experience watching people use godep:

Currently, if someone wants to fetch history for a package, a tool such as the go tool or godep can infer a URL from the package's import path. However, sometimes people maintain a temporary fork of a dependency, so they can keep patches up to date while waiting for those patches to be merged upstream. When doing so, it is common and a good idea to keep the original import path of the upstream package unchanged, and to vendor the patched code using a vendoring tool. This works fine until someone needs to collaborate on the fork's patch. Any package management tool won't know where to find the fork's history—it will have ready access to only the upstream history and the vendored code. The JSON file will likely specify a revision that doesn't exist in the upstream history.

One possible solution to this would be to add an optional field to the Package struct that specifies an alternative location where the package's history can be obtained:

```
Package []struct {
    ...

    // AltURL provides an alternative place to download
    // the history of the package. Optional.
    AltURL string
}
```

Some package management tools have a function to check out the history and the specified revision of a vendored package into the user's GOPATH. (For example, `godep restore`.) If AltURL is present, such a tool could use it instead of (or in addition to) the upstream URL inferred from the import path. This lets it know where to find the fork's history, which should include the revision listed in the JSON file.

**Comment by kardianos** [comment]
This is an interesting idea.

Right now my vendor tool doesn't currently fetch specific revisions so I
have little experience with implementing a workflow like this. Due to my
inexperience I'm not sure if this would be a tool specific field or a spec
field.

**Comment by kr** [comment]
It's a lot easier to add things to the spec than to remove them, so if there's any doubt, I would recommend not adding it yet. Mostly I wanted to start the discussion about this problem.

**Comment by kardianos** [comment]
Agreed on both counts. Thank you for doing so. :)
